meta_product_name: "Carat"
meta_title: "Carat - Intelligent Commuting"
meta_description: "Carat uses routing intelligence to deliver the best ways to commute workers faster to work while saving companies money with transportation."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
